// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/wdstar/srcclr-cli/client/issues"
	"github.com/wdstar/srcclr-cli/client/registry"
	"github.com/wdstar/srcclr-cli/client/scans"
	"github.com/wdstar/srcclr-cli/client/workspaces"
)

// Default veracode source clear API specification HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.sourceclear.io"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new veracode source clear API specification HTTP client.
func NewHTTPClient(formats strfmt.Registry) *VeracodeSourceClearAPISpecification {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new veracode source clear API specification HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *VeracodeSourceClearAPISpecification {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new veracode source clear API specification client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *VeracodeSourceClearAPISpecification {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(VeracodeSourceClearAPISpecification)
	cli.Transport = transport

	cli.Issues = issues.New(transport, formats)

	cli.Registry = registry.New(transport, formats)

	cli.Scans = scans.New(transport, formats)

	cli.Workspaces = workspaces.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// VeracodeSourceClearAPISpecification is a client for veracode source clear API specification
type VeracodeSourceClearAPISpecification struct {
	Issues *issues.Client

	Registry *registry.Client

	Scans *scans.Client

	Workspaces *workspaces.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *VeracodeSourceClearAPISpecification) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Issues.SetTransport(transport)

	c.Registry.SetTransport(transport)

	c.Scans.SetTransport(transport)

	c.Workspaces.SetTransport(transport)

}
