// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLibraryUsingGETParams creates a new GetLibraryUsingGETParams object
// with the default values initialized.
func NewGetLibraryUsingGETParams() *GetLibraryUsingGETParams {
	var ()
	return &GetLibraryUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLibraryUsingGETParamsWithTimeout creates a new GetLibraryUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLibraryUsingGETParamsWithTimeout(timeout time.Duration) *GetLibraryUsingGETParams {
	var ()
	return &GetLibraryUsingGETParams{

		timeout: timeout,
	}
}

// NewGetLibraryUsingGETParamsWithContext creates a new GetLibraryUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLibraryUsingGETParamsWithContext(ctx context.Context) *GetLibraryUsingGETParams {
	var ()
	return &GetLibraryUsingGETParams{

		Context: ctx,
	}
}

// NewGetLibraryUsingGETParamsWithHTTPClient creates a new GetLibraryUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLibraryUsingGETParamsWithHTTPClient(client *http.Client) *GetLibraryUsingGETParams {
	var ()
	return &GetLibraryUsingGETParams{
		HTTPClient: client,
	}
}

/*GetLibraryUsingGETParams contains all the parameters to send to the API endpoint
for the get library using g e t operation typically these are written to a http.Request
*/
type GetLibraryUsingGETParams struct {

	/*ID
	  id

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get library using g e t params
func (o *GetLibraryUsingGETParams) WithTimeout(timeout time.Duration) *GetLibraryUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get library using g e t params
func (o *GetLibraryUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get library using g e t params
func (o *GetLibraryUsingGETParams) WithContext(ctx context.Context) *GetLibraryUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get library using g e t params
func (o *GetLibraryUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get library using g e t params
func (o *GetLibraryUsingGETParams) WithHTTPClient(client *http.Client) *GetLibraryUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get library using g e t params
func (o *GetLibraryUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get library using g e t params
func (o *GetLibraryUsingGETParams) WithID(id string) *GetLibraryUsingGETParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get library using g e t params
func (o *GetLibraryUsingGETParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetLibraryUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
