// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/wdstar/srcclr-cli/models"
)

// GetLibraryUsingGETReader is a Reader for the GetLibraryUsingGET structure.
type GetLibraryUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLibraryUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetLibraryUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLibraryUsingGETOK creates a GetLibraryUsingGETOK with default headers values
func NewGetLibraryUsingGETOK() *GetLibraryUsingGETOK {
	return &GetLibraryUsingGETOK{}
}

/*GetLibraryUsingGETOK handles this case with default header values.

OK
*/
type GetLibraryUsingGETOK struct {
	Payload *models.Library
}

func (o *GetLibraryUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /v3/libraries/{id}][%d] getLibraryUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetLibraryUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Library)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
