# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
- env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GITHUB_OWNER=wdstar
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  #- 386
  ldflags:
  - -s -w
    -X github.com/{{.Env.GITHUB_OWNER}}/{{.ProjectName}}/cmd.version={{.Version}}
    -X github.com/{{.Env.GITHUB_OWNER}}/{{.ProjectName}}/cmd.commit={{.Commit}}
    -X github.com/{{.Env.GITHUB_OWNER}}/{{.ProjectName}}/cmd.date={{.Date}}
    -X github.com/{{.Env.GITHUB_OWNER}}/{{.ProjectName}}/cmd.builtBy=goreleaser
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
