// Code generated by go-swagger; DO NOT EDIT.

package issues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/wdstar/srcclr-cli/models"
)

// GetIssueUsingGETReader is a Reader for the GetIssueUsingGET structure.
type GetIssueUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIssueUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetIssueUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetIssueUsingGETOK creates a GetIssueUsingGETOK with default headers values
func NewGetIssueUsingGETOK() *GetIssueUsingGETOK {
	return &GetIssueUsingGETOK{}
}

/*GetIssueUsingGETOK handles this case with default header values.

OK
*/
type GetIssueUsingGETOK struct {
	Payload *models.Issue
}

func (o *GetIssueUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /v3/issues/{id}][%d] getIssueUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetIssueUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Issue)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
