// Code generated by go-swagger; DO NOT EDIT.

package workspaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/wdstar/srcclr-cli/models"
)

// GetIssuesUsingGETReader is a Reader for the GetIssuesUsingGET structure.
type GetIssuesUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIssuesUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetIssuesUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetIssuesUsingGETOK creates a GetIssuesUsingGETOK with default headers values
func NewGetIssuesUsingGETOK() *GetIssuesUsingGETOK {
	return &GetIssuesUsingGETOK{}
}

/*GetIssuesUsingGETOK handles this case with default header values.

OK
*/
type GetIssuesUsingGETOK struct {
	Payload *models.PagedResourcesIssue
}

func (o *GetIssuesUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /v3/workspaces/{id}/issues][%d] getIssuesUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetIssuesUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PagedResourcesIssue)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
