// Code generated by go-swagger; DO NOT EDIT.

package workspaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new workspaces API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for workspaces API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetIssuesUsingGET gets issues

Get issues for the given workspace. Note: if a project Default Branch is set, only issues from scans of that branch will be displayed.
*/
func (a *Client) GetIssuesUsingGET(params *GetIssuesUsingGETParams) (*GetIssuesUsingGETOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetIssuesUsingGETParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getIssuesUsingGET",
		Method:             "GET",
		PathPattern:        "/v3/workspaces/{id}/issues",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetIssuesUsingGETReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetIssuesUsingGETOK), nil

}

/*
GetWorkspaceUsingGET gets workspace

Get single workspace.
*/
func (a *Client) GetWorkspaceUsingGET(params *GetWorkspaceUsingGETParams) (*GetWorkspaceUsingGETOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetWorkspaceUsingGETParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getWorkspaceUsingGET",
		Method:             "GET",
		PathPattern:        "/v3/workspaces/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetWorkspaceUsingGETReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetWorkspaceUsingGETOK), nil

}

/*
GetWorkspacesUsingGET gets workspaces

Get visible workspaces. Workspace visibility depends on workspace membership and user permissions.
*/
func (a *Client) GetWorkspacesUsingGET(params *GetWorkspacesUsingGETParams) (*GetWorkspacesUsingGETOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetWorkspacesUsingGETParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getWorkspacesUsingGET",
		Method:             "GET",
		PathPattern:        "/v3/workspaces",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetWorkspacesUsingGETReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetWorkspacesUsingGETOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
